name: NodeJS with Webpack

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-youtube-extension:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: '16'

    - name: Build
      run: |
        cd youTubeExtension
        npm install
        npm run package:linux
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-youtube-extension
        path: "./youTubeExtension/dist"
